# Generated by Django 4.2 on 2024-02-01 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchandises', '0002_auto_20231207_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchandises', to='merchandises.category'),
        ),
    ]
